export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:5000/api' : 'something'

export const LOCAL_STORAGE = 'accessToken'

export const ROOM_LOAD_SUCCESS = 'ROOM_LOAD_SUCCESS'
export const ROOM_LOAD_FAILED = 'ROOM_LOAD_FAILED'
export const ROOM_ADD = 'ROOM_ADD'
export const ROOM_DELETE = 'ROOM_DELETE'
export const ROOM_FIND = 'ROOM_FIND'
export const ROOM_UPDATE = 'ROOM_UPDATE'

export const CUSTOMER_LOAD_SUCCESS = "CUSTOMER_LOAD_SUCCESS"
export const CUSTOMER_LOAD_FAILED = "CUSTOMER_LOAD_FAILED"
export const CUSTOMER_ADD = "CUSTOMER_ADD"
export const CUSTOMER_UPDATE = "CUSTOMER_UPDATE"
export const CUSTOMER_FIND = "CUSTOMER_FIND"
export const CUSTOMER_DELETE = "CUSTOMER_DELETE"

export const POST_LOAD_SUCCESS = "POST_LOAD_SUCCESS"
export const POST_LOAD_FAILED = "POST_LOAD_FAILED"
export const POST_ADD = 'POST_ADD'
export const POST_FIND = "POST_FIND"
export const POST_DELETE = "POST_DELETE"


export const SERVICE_LOAD_SUCCESS = 'SERVICE_LOAD_SUCCESS'
export const SERVICE_LOAD_FAILED = 'SERVICE_LOAD_FAILED'
export const SERVICE_ADD = 'SERVICE_ADD'
export const SERVICE_FIND = "SERVICE_FIND"
export const SERVICE_UPDATE = 'SERVICE_UPDATE'
export const SERVICE_DELETE = 'SERVICE_DELETE'

export const RECEIPT_LOAD_SUCCESS = 'RECEIPT_LOAD_SUCCESS'
export const RECEIPT_LOAD_FAILED = 'RECEIPT_LOAD_FAILED'
export const RECEIPT_ADD = 'RECEIPT_ADD'
export const RECEIPT_FIND = "RECEIPT_FIND"
export const RECEIPT_UPDATE = 'RECEIPT_UPDATE'
export const RECEIPT_DELETE = 'RECEIPT_DELETE'


export const TOTAL_LOAD_SUCCESS = 'TOTAL_LOAD_SUCCESS'
export const TOTAL_LOAD_FAILED = 'TOTAL_LOAD_FAILED'
export const TOTAL_ADD = 'TOTAL_ADD'
export const TOTAL_FIND = "TOTAL_FIND"
export const TOTAL_UPDATE = 'TOTAL_UPDATE'
export const TOTAL_DELETE = 'TOTAL_DELETE'

export const BILL_LOAD_SUCCESS = 'BILL_LOAD_SUCCESS'
export const BILL_LOAD_FAILED = 'BILL_LOAD_FAILED'
export const BILL_ADD = 'BILL_ADD'
export const BILL_FIND = "BILL_FIND"
export const BILL_UPDATE = 'BILL_UPDATE'
export const BILL_DELETE = 'BILL_DELETE'